services:
  # Base de datos del proyecto principal
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: redis_queue
    restart: unless-stopped
    command: sh -c 'redis-server --requirepass "$${REDIS_PASSWORD}"'
    env_file:
      - .env
    volumes:
      - redis_data:/data
    networks:
      - app_network

  # Aplicación NestJS
  api:
    # IMPORTANTE: Cambia "TU_USUARIO" y "TU_REPOSITORIO" por los reales de GitHub
    image: ghcr.io/devangelcrow/inventory_backend:latest
    container_name: nest_app
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: ${DB_PORT}
      DATABASE_USER: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_NAME: ${DB_NAME}
      NODE_ENV: production
    ports:
      # Exponemos a localhost para que el proxy reverso (Nginx) lo tome seguro
      - "127.0.0.1:3000:3000"
    networks:
      - app_network

  # Worker de NestJS (BullMQ)
  worker:
    # IMPORTANTE: Cambia "TU_USUARIO" y "TU_REPOSITORIO" por los reales de GitHub
    image: ghcr.io/devangelcrow/inventory_backend:latest
    container_name: nest_worker
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: ${DB_PORT}
      DATABASE_USER: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_NAME: ${DB_NAME}
      NODE_ENV: production
    command: npm run start:worker:prod
    networks:
      - app_network

volumes:
  postgres_data:
  redis_data:

networks:
  app_network:
    driver: bridge
