// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';
let url = '';
let seedCommand = '';
const dbHost = process.env.DATABASE_HOST || process.env.DB_HOST;
url = `${process.env.DB_PROVIDER}://${process.env.DB_USER}:${process.env.DB_PASSWORD}@${dbHost}:${process.env.DB_PORT}/${process.env.DB_NAME}?schema=public&timezone=UTC`;

if (process.env.NODE_ENV === 'production') {
  seedCommand = 'node dist/prisma/seeds/main.seeder.js';
} else {
  seedCommand = 'tsx prisma/seeds/main.seeder.ts';
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: seedCommand,
  },
  datasource: {
    url: url,
  },
});
