// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';
let url = '';
let seedCommand = '';
if (process.env.NODE_ENV === 'production') {
  url = process.env.DATABASE_DIRECT_URL!;
  seedCommand = 'node dist/prisma/seeds/main.seeder.js';
  /*`${env('DATABASE_URL')}`;*/
} else {
  url = `${process.env.DB_PROVIDER}://${process.env.DB_USER}:${process.env.DB_PASSWORD}@${process.env.DB_HOST}:${process.env.DB_PORT}/${process.env.DB_NAME}?schema=public&timezone=UTC`;
  seedCommand = 'tsx prisma/seeds/main.seeder.ts';
  //`${env('DB_PROVIDER')}://${env('DB_USER')}:${env('DB_PASSWORD')}@${env('DB_HOST')}:${env('DB_PORT')}/${env('DB_NAME')}?schema=public&timezone=UTC`;
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: seedCommand,
  },
  datasource: {
    url: url,
  },
});
