# Información del proyecto
sonar.projectKey=backend_template_nest
sonar.projectName=backend_template_nest
sonar.projectVersion=0.0.1

# URL del servidor SonarQube (local)
sonar.host.url=http://localhost:9000

# Directorio de código fuente
sonar.sources=src

#token
sonar.token = 

# Exclusiones
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.spec.ts,**/prisma/**,**/migrations/**, **/*.py, **/*.c, **/*.cpp, **/*.h

# Encoding
sonar.sourceEncoding=UTF-8

#SCM Provider
sonar.scm.provider=git