export enum ErrorCode {
  // Auth
  AUTH_INVALID_CREDENTIALS = 'AUTH_001',
  AUTH_EMAIL_NOT_VERIFIED = 'AUTH_002',
  AUTH_ACCOUNT_LOCKED = 'AUTH_003',
  AUTH_TOKEN_EXPIRED = 'AUTH_004',
  // Validation
  VALIDATION_FAILED = 'VAL_001',
  // Resources
  RESOURCE_NOT_FOUND = 'RES_001',
  RESOURCE_CONFLICT = 'RES_002',
  // Security
  FORBIDDEN = 'SEC_001',
  UNAUTHORIZED = 'SEC_002',
  // Infrastructure
  INTERNAL_SERVER_ERROR = 'SRV_001',
  SERVICE_UNAVAILABLE = 'SRV_002',
  BAD_GATEWAY = 'SRV_003',
}
