export enum AuditAction {
  // Authentication / session
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGOUT = 'LOGOUT',
  REVOKE_ALL_SESSIONS = 'REVOKE_ALL_SESSIONS',
  TOKEN_REFRESH = 'TOKEN_REFRESH',
  REGISTER = 'REGISTER',
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED',
  DOCS_ACCESS_GRANTED = 'DOCS_ACCESS_GRANTED',
  DOCS_ACCESS_DENIED = 'DOCS_ACCESS_DENIED',
  // User management (privilege actions — audit-critical)
  USER_CREATED_BY_ADMIN = 'USER_CREATED_BY_ADMIN',
  // Role management
  ROLE_CREATED = 'ROLE_CREATED',
  ROLE_UPDATED = 'ROLE_UPDATED',
  ROLE_STATUS_TOGGLED = 'ROLE_STATUS_TOGGLED',
  // Permission management
  PERMISSION_CREATED = 'PERMISSION_CREATED',
  PERMISSION_UPDATED = 'PERMISSION_UPDATED',
  PERMISSION_STATUS_TOGGLED = 'PERMISSION_STATUS_TOGGLED',
}
